// Type declarations for the Emscripten-generated WASM module (CommonJS format).
// The actual openjp2.js + openjp2.wasm are generated by core/build-wasm.sh.

export interface OpenjpegModule {
  _decode_jp2(
    inputPtr: number,
    inputLen: number,
    widthPtr: number,
    heightPtr: number,
    channelsPtr: number,
  ): number
  _free_buffer(ptr: number): void
  _malloc(size: number): number
  _free(ptr: number): void
  HEAPU8: Uint8Array
  getValue(ptr: number, type: string): number
}

declare function createOpenjpegModule(options?: Record<string, unknown>): Promise<OpenjpegModule>

export = createOpenjpegModule
