name: Quarkus Native Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Package
    if: ${{ contains(github.event.head_commit.message, 'chore(main):') }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '17'
        components: 'native-image'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build with Maven (Native)
      run: |
        cd core
        mvn clean package -Pnative -Dquarkus.package.output-directory=
    
    - name: Prepare artifacts
      run: |
        mkdir -p bin
        cp core/target/*-runner bin/
        cp -r core/target/lib bin/ || echo "No lib directory found"
        cp -r core/target/quarkus-app bin/ || echo "No quarkus-app directory found"
        
        # Clean up unnecessary files
        rm -rf core/target/*.jar || true
        rm -rf core/target/*.original || true
        rm -rf core/target/classes || true
        rm -rf core/target/maven-* || true
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: quarkus-native-package
        path: bin/

  release:
    name: Process Release
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Process Release Please
      uses: googleapis/release-please-action@v4
      id: release-please
      with:
        config-file: release-please-config.json
        manifest-file: .release-please-manifest.json
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Print release outputs for debugging
      continue-on-error: true
      run: |
        echo "Release outputs:"
        echo "${{ toJson(steps.release-please.outputs) }}"

    - name: Download build artifacts
      if: ${{ steps.release-please.outputs.releases_created == 'true' }}
      uses: actions/download-artifact@v4
      with:
        name: quarkus-native-package
        path: lib/bin/

    - name: Setup Node.js for NPM Publishing
      if: ${{ steps.release-please.outputs.releases_created == 'true' }}
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'

    - name: Enable Corepack and Setup Yarn
      run: |
        corepack enable
        corepack prepare yarn@3.6.1 --activate
        yarn --version
        
    - name: Publish to NPM
      if: ${{ steps.release-please.outputs.releases_created == 'true' }}
      run: |
        cd lib
        yarn install --immutable
        yarn build
        echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
        yarn config set npmAuthToken ${NPM_AUTH_TOKEN}
        yarn npm publish --access public
      env:
         NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}