name: Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Package
    if: ${{ contains(github.event.head_commit.message, 'chore(main):') }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenjp2-7-dev build-essential

      - name: Install dependencies (macOS only)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install openjpeg

      - name: Set up MSVC Compiler (Windows only)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile C binary
        run: |
          mkdir -p bin

          if [ "$RUNNER_OS" == "Linux" ]; then
            gcc core/convert.c -o bin/convert-linux -static -lopenjp2 -lm
          elif [ "$RUNNER_OS" == "macOS" ]; then
            clang core/convert.c -o bin/convert-mac -lopenjp2 -lm
          elif [ "$RUNNER_OS" == "Windows" ]; then
            cl /O2 /Fe:bin\\convert-win.exe core\\convert.c openjp2.lib
          fi
        shell: bash

      - name: Upload compiled binary
        uses: actions/upload-artifact@v4
        with:
          name: convert-binaries
          path: bin/

  release:
    name: Process Release
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Process Release Please
      uses: googleapis/release-please-action@v4
      id: release-please
      with:
        config-file: release-please-config.json
        manifest-file: .release-please-manifest.json
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Print release outputs for debugging
      continue-on-error: true
      run: |
        echo "Release outputs:"
        echo "${{ toJson(steps.release-please.outputs) }}"

    - name: Download build artifacts
      if: ${{ steps.release-please.outputs.releases_created == 'true' }}
      uses: actions/download-artifact@v4
      with:
        name: convert-binaries
        path: lib/src/bin/

    - name: Setup Node.js for NPM Publishing
      if: ${{ steps.release-please.outputs.releases_created == 'true' }}
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'

    - name: Enable Corepack and Setup Yarn
      run: |
        corepack enable
        corepack prepare yarn@3.6.1 --activate
        yarn --version
        
    - name: Publish to NPM
      if: ${{ steps.release-please.outputs.releases_created == 'true' }}
      run: |
        cd lib
        yarn install --immutable
        yarn build
        rm -rf src/bin/
        echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
        yarn config set npmAuthToken ${NPM_AUTH_TOKEN}
        yarn npm publish --access public
      env:
         NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}