name: Continuous Integration

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout jp2-to-image
        uses: actions/checkout@v4

      - name: Enable Corepack (for Yarn 3+)
        run: |
          sudo corepack enable

      - name: Setup Node.js v20 with Yarn 3.6.1
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Enable Yarn 3.6.1
        run: |
          yarn set version 3.6.1
          yarn --version
          
      - name: Install dependencies
        run: |
          cd lib
          yarn install --immutable

      - name: Build
        run: |
          cd lib
          yarn build

      - name: Check Format
        run: |
          cd lib
          yarn check-format

      - name: Check Types
        run: |
          cd lib
          yarn check-types