name: Release to NPM
on:
  workflow_run:
    workflows: ["Quarkus Native Build"]
    types:
      - completed
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:

  release:
    name: Process Release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Process Release Please
      uses: googleapis/release-please-action@v4
      id: release-please
      with:
        config-file: release-please-config.json
        manifest-file: .release-please-manifest.json
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Print release outputs for debugging
      continue-on-error: true
      run: |
        echo "Release outputs:"
        echo "${{ toJson(steps.release-please.outputs) }}"

    - name: Download build artifacts
      if: ${{ steps.release-please.outputs.releases_created == 'true' }}
      uses: actions/download-artifact@v4
      with:
        name: quarkus-native-package
        path: bin/
        workflow: Quarkus Native Build

    - name: Setup Node.js for NPM Publishing
      if: ${{ steps.release-please.outputs.releases_created == 'true' }}
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Publish to NPM
      if: ${{ steps.release-please.outputs.releases_created == 'true' }}
      run: |
        cd lib
        yarn install --immutable
        yarn npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
